services:
  postgres:
    image: pgvector/pgvector:pg17  # Official image with pgvector pre-installed
    # use pg16 or pg15 if needed
    container_name: pgvector-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgvector-test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: